sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_outnew
    username: root
    password: root
  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:
  redis:
    host: localhost
    password: 123456
    port: 6379
    database: 2
  wechat:
    appid: wxb45627336a33061a
    secret: 4c16eb27e7518e91d65fca71ff64c82c
